rabbitmq:
  image: rabbitmq:3-management
  hostname: jrabbit
  restart: always
  ports:
  - 127.0.0.1:5672:5672 # port for the daemon API, can be exposed to public.
  - 127.0.0.1:15672:15672 # port for the Management interface
  env_file:
    - .secret.rabbitmq
  volumes:
  - /etc/localtime:/etc/localtime:ro
  volumes_from:
  - rabbitmq_data
rabbitmq_data:
  image: busybox
  tty: true
  command: chown -v -R 999:999 /data/rabbitmq
  volumes:
  - /data/rabbitmq
  stdin_open: true

redis:
  image: redis
  hostname: jredis
  restart: always
  ports:
  - 127.0.0.1:6379:6379 # port for redis server
  volumes:
  - /data/redis:/data
  restart: always

mysql:
  image: mysql
  hostname: jmysql
  ports:
    - "127.0.0.1:3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: NeDjqJEp
    MYSQL_USER: dev
    MYSQL_PASSWORD: 72zjhTWh
    MYSQL_DATABASE: myapp
  volumes:
  - "/data/mysql:/var/lib/mysql"
  restart: always